### ISSUE TITLE
Fetching parent keys returns "Undefined index"

### ISSUE THREAD

**Issue by YOzaz** [bradcornford/Setter#14]
Let's say, I have such setting in a config:

``` php
/* myconfig.php */
return [
   'triggers' => [
      'ctr' => 15,
      'cpc' => 16
   ]
];
```

In an app, I fetch these values using your package:

``` php
$triggers = Setting::get('myconfig.triggers');
```

Works fine, as it gets values from Config. Then, let's say, we want to change one (only one) value of it:

``` php
Setting::set('myconfig.triggers.ctr', 20);
```

Now, when I call same "get", I get an exception:

```
ErrorException (E_UNKNOWN)
Undefined index: myconfig.triggers
/vendor/cornford/setter/src/Cornford/Setter/SettingBase.php:142
Code: if ($results[$key] === '""') {
```

... and not sure how to fix it. I believe here you've just got a value from database with index "myconfig.triggers.ctr" - so probably can just grab and use it instead? Like:

``` php
$key = reset( array_keys($results) );
```

**Comment by YOzaz** [comment]
Happy New Year!
Didn't make thorough tests on this, but from initial perspective it looks like it works correctly. Thanks!

**Comment by bradcornford** [comment]
Happy new year!

No worries. Hope you find this package useful =)
